version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env 
    networks:
      - mern-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

      